dbt_lindy:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ZVIAMOM-IN09435
      user: CSAW
      password: Qwertasdfg@1469
      role: ACCOUNTADMIN
      database: LINDY_CREDIT_INTELLIGENCE
      warehouse: COMPUTE_WH
      schema: MARTS
      threads: 4
      client_session_keep_alive: false